imports:
- path: bucket.jinja
- path: service_account.jinja
- path: instance.jinja

resources:
- name: access
  type: service_account.jinja
  properties:
    nonce: "//nonce//"
    permissions: 
    - compute.instances.get
    - compute.instances.list
- name: bucket
  type: bucket_acl.jinja
  properties:
    predefinedAcl: private
    nonce: "//nonce//"
    service_account: access-level2
    service_account_role: READER
- name: log-instance
  type: instance.jinja
  properties:
    zone: us-west1-b
    ssh_public_key: //ssh_public_key//
    ssh_username: //ssh_username//
    startup_script: //startup_script//
    sa_properties:
    - role: roles/logging.viewer